
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 06 00:56:08 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 12;
  public static final int PLUS = 15;
  public static final int QUIT = 7;
  public static final int SEMI = 21;
  public static final int LEFTPAR = 17;
  public static final int CRAFTINT = 4;
  public static final int RIGHTPAR = 18;
  public static final int ID = 13;
  public static final int HMM = 10;
  public static final int COMMA = 22;
  public static final int CRAFT = 3;
  public static final int CREATEWORLD = 2;
  public static final int EOF = 0;
  public static final int DOTDOT = 19;
  public static final int TRADE = 11;
  public static final int DOT = 23;
  public static final int CONST = 14;
  public static final int error = 1;
  public static final int ASSIGN = 20;
  public static final int START = 6;
  public static final int MUL = 16;
  public static final int MINE = 8;
  public static final int SMELT = 9;
  public static final int CRAFTCHAR = 5;
}

